name: Hoyvin Glavin!
description: On technical minutiae, by Jeff Lee
url: http://hoyvinglavin.com

exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
permalink: pretty

gems:
  - jekyll-redirect-from

kramdown:
  input: GFM